MODEL (
  name JDE_PRODUCTION.RL_JDE_VULCAN.FACTARCOLLECTION,
  kind INCREMENTAL_BY_UNIQUE_KEY (
    unique_key (COMPANYID, CUSTOMERNUMBER, FISCALPERIODID, LOB)
  ),
  grains (COMPANYID, CUSTOMERNUMBER, FISCALPERIODID, LOB),
  tags ('ACCOUNTS_RECEIVABLE', 'FACT', 'COLLECTIONS', 'GOLD'),
  column_descriptions (
    COMPANYID = 'JDE company identifier.',
    CUSTOMERNUMBER = 'Customer identifier.',
    FISCALPERIODID = 'Fiscal period key.',
    LOB = 'Line of business code.',
    LOBCODE = 'Line of business code (join key to DIMARCOLLECTIONLOB).',
    TOTALRECEIPTS = 'Total receipts.',
    CASHAPPLIED = 'Cash applied amount.',
    COLLECTIONEFFICIENCY = 'Collection efficiency ratio.',
    OPENARATPERIODSTART = 'Open AR denominator component for CEI.',
    RECEIPTCOUNT = 'Number of receipts in period.',
    FISCALYEAR = 'Derived fiscal year.',
    FISCALMONTH = 'Derived fiscal month.',
    INSERTDATE = 'Row load timestamp.'
  ),
  column_tags (
    COMPANYID = ('GRAIN', 'JOIN_KEY'),
    CUSTOMERNUMBER = ('GRAIN', 'CUSTOMER'),
    FISCALPERIODID = ('GRAIN', 'TIME_DIMENSION'),
    LOB = ('GRAIN', 'LOB'),
    LOBCODE = ('DIMENSION', 'LOB'),
    TOTALRECEIPTS = ('MEASURE', 'FINANCIAL'),
    CASHAPPLIED = ('MEASURE', 'FINANCIAL'),
    COLLECTIONEFFICIENCY = ('MEASURE', 'RATIO'),
    OPENARATPERIODSTART = ('MEASURE', 'FINANCIAL'),
    RECEIPTCOUNT = ('MEASURE', 'VOLUME'),
    FISCALYEAR = ('DIMENSION', 'PERIOD'),
    FISCALMONTH = ('DIMENSION', 'PERIOD')
  ),
  assertions (
    not_null(columns := (COMPANYID, CUSTOMERNUMBER, FISCALPERIODID, LOB)),
    unique_combination_of_columns(columns := (COMPANYID, CUSTOMERNUMBER, FISCALPERIODID, LOB)),
    ar_cash_applied_exceeds_receipts,
    ar_period_all_companies_present
  )
);

WITH RECEIPT_AGG AS (
  SELECT
    @normalize_key(R.RCCO) AS COMPANYID,
    @normalize_key(COALESCE(P.RNAN8, R.RCAN8)) AS CUSTOMERNUMBER,
    CAST(R.RCRP AS BIGINT) AS FISCALPERIODID,
    @normalize_key(COALESCE(LOB.LOBCODE, R.RCAID, 'UNMAPPED')) AS LOB,
    MIN(@normalize_key(R.RCMCU)) AS BUSINESSUNIT,
    MIN(CAST(NULL AS VARCHAR)) AS PAYMENTTERMCODE,
    SUM(TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.RCAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2))) AS TOTALRECEIPTS,
    SUM(TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.RCAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2))) AS CASHAPPLIED,
    SUM(CAST(0 AS DECIMAL(18, 2))) AS RESERVECASH,
    SUM(TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.RCAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2))) AS ADJUSTEDCOLLECTION,
    COUNT(*) AS RECEIPTCOUNT
  FROM STAGING.F03B14 R
  LEFT JOIN STAGING.F03B13 P
    ON @normalize_key(R.RCDOC) = @normalize_key(P.RNDOC)
    AND @normalize_key(R.RCCO) = @normalize_key(P.RNCO)
  LEFT JOIN (
    SELECT
      @normalize_key(GACO) AS COMPANYID,
      @normalize_key(GAID) AS GLOFFSET,
      @normalize_key(GAID) AS LOBCODE
    FROM STAGING.F0012
  ) LOB
    ON @normalize_key(R.RCCO) = LOB.COMPANYID
    AND @normalize_key(R.RCAID) = LOB.GLOFFSET
  GROUP BY
    @normalize_key(R.RCCO),
    @normalize_key(COALESCE(P.RNAN8, R.RCAN8)),
    CAST(R.RCRP AS BIGINT),
    @normalize_key(COALESCE(LOB.LOBCODE, R.RCAID, 'UNMAPPED'))
),
OPEN_AR_BY_PERIOD AS (
  SELECT
    @normalize_key(RPCO) AS COMPANYID,
    @normalize_key(RPAN8) AS CUSTOMERNUMBER,
    @jde_fiscal_period_id(@jde_to_date(RPDGJ)) AS FISCALPERIODID,
    SUM(TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(RPAAP AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2))) AS OPENAR
  FROM STAGING.F03B11
  WHERE TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(RPAAP AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) > 0
  GROUP BY
    @normalize_key(RPCO),
    @normalize_key(RPAN8),
    @jde_fiscal_period_id(@jde_to_date(RPDGJ))
)
SELECT
  RA.COMPANYID,
  RA.CUSTOMERNUMBER,
  RA.FISCALPERIODID,
  RA.LOB,
  RA.LOB AS LOBCODE,
  RA.BUSINESSUNIT,
  RA.PAYMENTTERMCODE,
  RA.TOTALRECEIPTS,
  RA.CASHAPPLIED,
  RA.RESERVECASH,
  COALESCE(RA.ADJUSTEDCOLLECTION, RA.CASHAPPLIED + RA.RESERVECASH) AS ADJUSTEDCOLLECTION,
  COALESCE(OA.OPENAR, 0) AS OPENARATPERIODSTART,
  LEAST(
    @safe_ratio(RA.CASHAPPLIED, COALESCE(OA.OPENAR, 0) + RA.TOTALRECEIPTS),
    1.0
  ) AS COLLECTIONEFFICIENCY,
  RA.RECEIPTCOUNT,
  FLOOR(RA.FISCALPERIODID / 100) AS FISCALYEAR,
  MOD(RA.FISCALPERIODID, 100) AS FISCALMONTH,
  CURRENT_TIMESTAMP() AS INSERTDATE
FROM RECEIPT_AGG RA
LEFT JOIN OPEN_AR_BY_PERIOD OA
  ON OA.COMPANYID = RA.COMPANYID
  AND OA.CUSTOMERNUMBER = RA.CUSTOMERNUMBER
  AND OA.FISCALPERIODID = RA.FISCALPERIODID;
