MODEL (
  name JDE_PRODUCTION.RL_JDE_VULCAN.FACTDSO,
  kind FULL,
  grains (COMPANYID, FISCALYEAR, FISCALMONTH, COLLECTIONPRIORITY),
  tags ('ACCOUNTS_RECEIVABLE', 'FACT', 'DSO', 'DISPUTES', 'GOLD'),
  column_descriptions (
    COMPANYID = 'JDE company identifier.',
    FISCALYEAR = 'Fiscal year.',
    FISCALMONTH = 'Fiscal month (1-12).',
    COLLECTIONPRIORITY = 'Collection priority segment H/M/L/NONE.',
    TOTALOPENAR = 'Sum of open amounts in segment/period.',
    TOTALGROSSINVOICED = 'Sum of gross invoiced in period.',
    DSO = 'Days Sales Outstanding.',
    DISPUTEDAMOUNTROLLING30 = 'Disputed sum where dispute date >= CURRENT_DATE - 30 days.',
    DISPUTERECOVERYRATIO = 'Proportion recovered on resolved disputes.',
    CEI = 'Unified collection effectiveness index for segment.',
    INSERTDATE = 'Row load timestamp.'
  ),
  column_tags (
    COMPANYID = ('GRAIN', 'JOIN_KEY'),
    FISCALYEAR = ('GRAIN', 'TIME_DIMENSION'),
    FISCALMONTH = ('GRAIN', 'TIME_DIMENSION'),
    COLLECTIONPRIORITY = ('GRAIN', 'PRIORITY'),
    DSO = ('MEASURE', 'KPI'),
    CEI = ('MEASURE', 'KPI')
  )
);

WITH INVOICE_BASE AS (
  SELECT
    @normalize_key(B.RPCO) AS COMPANYID,
    YEAR(@jde_to_date(B.RPDGJ)) AS FISCALYEAR,
    MONTH(@jde_to_date(B.RPDGJ)) AS FISCALMONTH,
    COALESCE(NULLIF(@normalize_key(CR.ACAPTS2), ''), 'NONE') AS COLLECTIONPRIORITY,
    TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS OPENAMOUNT,
    TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPAAP AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS GROSSAMOUNT,
    TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPDPAM AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS DISPUTEAMOUNT,
    NULLIF(@normalize_key(B.RPADSC), '') AS DISPUTECODE,
    @normalize_key(B.RPASTS) AS PAYMENTSTATUS,
    PT.PTNDDY AS NETDAYS,
    COALESCE(@jde_to_date(B.RPDPDT), @jde_to_date(B.RPDGJ)) AS DISPUTEDATEANCHOR,
    @jde_to_date(B.RPDGJ) AS GLDATE
  FROM STAGING.F03B11 B
  LEFT JOIN STAGING.F03012 CR
    ON @normalize_key(B.RPAN8) = @normalize_key(CR.ACAN8)
   AND @normalize_key(B.RPCO) = @normalize_key(CR.ACCO)
  LEFT JOIN STAGING.F0014 PT
    ON @normalize_key(B.RPPTC) = @normalize_key(PT.PTC)
),
PERIOD_AGG AS (
  SELECT
    COMPANYID,
    FISCALYEAR,
    FISCALMONTH,
    COLLECTIONPRIORITY,
    SUM(OPENAMOUNT) AS TOTALOPENAR,
    SUM(GROSSAMOUNT) AS TOTALGROSSINVOICED,
    DATEDIFF(
      'DAY',
      DATE_FROM_PARTS(MIN(FISCALYEAR), MIN(FISCALMONTH), 1),
      DATEADD('MONTH', 1, DATE_FROM_PARTS(MIN(FISCALYEAR), MIN(FISCALMONTH), 1))
    ) AS DAYSINPERIOD,
    AVG(NETDAYS) AS AVGCONTRACTUALNETDAYS,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL THEN COALESCE(DISPUTEAMOUNT, OPENAMOUNT) ELSE 0 END) AS DISPUTEDAMOUNTTOTAL,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND DISPUTEDATEANCHOR >= DATEADD('DAY', -30, CURRENT_DATE())
             THEN COALESCE(DISPUTEAMOUNT, OPENAMOUNT) ELSE 0 END) AS DISPUTEDAMOUNTROLLING30,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND DISPUTEDATEANCHOR >= DATEADD('DAY', -60, CURRENT_DATE())
             THEN COALESCE(DISPUTEAMOUNT, OPENAMOUNT) ELSE 0 END) AS DISPUTEDAMOUNTROLLING60,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND DISPUTEDATEANCHOR >= DATEADD('DAY', -90, CURRENT_DATE())
             THEN COALESCE(DISPUTEAMOUNT, OPENAMOUNT) ELSE 0 END) AS DISPUTEDAMOUNTROLLING90,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND DISPUTEDATEANCHOR >= DATEADD('DAY', -180, CURRENT_DATE())
             THEN COALESCE(DISPUTEAMOUNT, OPENAMOUNT) ELSE 0 END) AS DISPUTEDAMOUNTROLLING180,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND PAYMENTSTATUS <> 'D' THEN GROSSAMOUNT ELSE 0 END) AS RESOLVEDDISPUTEGROSS,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL AND PAYMENTSTATUS <> 'D' THEN GROSSAMOUNT - OPENAMOUNT ELSE 0 END) AS RESOLVEDDISPUTERECOVERED,
    COUNT(*) AS INVOICECOUNT,
    SUM(CASE WHEN DISPUTECODE IS NOT NULL THEN 1 ELSE 0 END) AS DISPUTEDINVOICECOUNT
  FROM INVOICE_BASE
  GROUP BY COMPANYID, FISCALYEAR, FISCALMONTH, COLLECTIONPRIORITY
)
SELECT
  COMPANYID,
  FISCALYEAR,
  FISCALMONTH,
  COLLECTIONPRIORITY,
  TOTALOPENAR,
  TOTALGROSSINVOICED,
  DAYSINPERIOD,
  CASE WHEN TOTALGROSSINVOICED > 0
       THEN ROUND((TOTALOPENAR / TOTALGROSSINVOICED) * DAYSINPERIOD, 2)
       ELSE 0 END AS DSO,
  ROUND(AVGCONTRACTUALNETDAYS, 0) AS AVGCONTRACTUALNETDAYS,
  CASE WHEN TOTALGROSSINVOICED > 0
       THEN ROUND((TOTALOPENAR / TOTALGROSSINVOICED) * DAYSINPERIOD - COALESCE(AVGCONTRACTUALNETDAYS, 0), 2)
       ELSE 0 END AS DSOVARIANCEFROMTERMS,
  DISPUTEDAMOUNTTOTAL,
  DISPUTEDAMOUNTROLLING30,
  DISPUTEDAMOUNTROLLING60,
  DISPUTEDAMOUNTROLLING90,
  DISPUTEDAMOUNTROLLING180,
  RESOLVEDDISPUTEGROSS,
  RESOLVEDDISPUTERECOVERED,
  CASE WHEN RESOLVEDDISPUTEGROSS > 0
       THEN ROUND(RESOLVEDDISPUTERECOVERED / RESOLVEDDISPUTEGROSS, 4)
       ELSE 0 END AS DISPUTERECOVERYRATIO,
  CASE WHEN TOTALGROSSINVOICED > 0
       THEN LEAST(ROUND((TOTALGROSSINVOICED - TOTALOPENAR) / TOTALGROSSINVOICED, 4), 1.0000)
       ELSE 0 END AS CEI,
  INVOICECOUNT,
  DISPUTEDINVOICECOUNT,
  CURRENT_TIMESTAMP() AS INSERTDATE
FROM PERIOD_AGG;
