MODEL (
  name JDE_PRODUCTION.RL_JDE_VULCAN.FACTARDETAILS,
  kind INCREMENTAL_BY_UNIQUE_KEY (
    unique_key (COMPANYID, DOCUMENTCOMPANY, DOCNO, DOCTYPE, PAYITM)
  ),
  grains (COMPANYID, DOCUMENTCOMPANY, DOCNO, DOCTYPE, PAYITM),
  tags ('ACCOUNTS_RECEIVABLE', 'FACT', 'FINANCE', 'GOLD'),
  column_descriptions (
    COMPANYID = 'JDE company identifier.',
    DOCUMENTCOMPANY = 'Document company identifier.',
    DOCNO = 'Document number.',
    DOCTYPE = 'Document type.',
    PAYITM = 'Pay item identifier.',
    OPENAMOUNT = 'Outstanding amount.',
    CURRENTRESERVE = 'Current reserve amount.',
    FORECASTRESERVE30 = '30-day reserve forecast.',
    CHANGEINRESERVE = 'Reserve delta for period.',
    AGINGDAYS = 'Invoice aging days.',
    FISCALPERIODID = 'Fiscal period key.',
    AGINGBUCKET = 'Derived aging bucket.',
    FISCALYEAR = 'Derived fiscal year.',
    FISCALMONTH = 'Derived fiscal month.',
    DISPUTEDATE = 'Date dispute was opened.',
    INSERTDATE = 'Row load timestamp.'
  ),
  column_tags (
    COMPANYID = ('GRAIN', 'JOIN_KEY'),
    DOCUMENTCOMPANY = ('GRAIN', 'JOIN_KEY'),
    DOCNO = ('GRAIN', 'JOIN_KEY'),
    DOCTYPE = ('GRAIN', 'JOIN_KEY'),
    PAYITM = ('GRAIN', 'JOIN_KEY'),
    OPENAMOUNT = ('MEASURE', 'FINANCIAL'),
    CURRENTRESERVE = ('MEASURE', 'RESERVE'),
    FISCALPERIODID = ('TIME_DIMENSION', 'PERIOD'),
    AGINGBUCKET = ('DIMENSION', 'AGING'),
    FISCALYEAR = ('DIMENSION', 'PERIOD'),
    FISCALMONTH = ('DIMENSION', 'PERIOD')
  ),
  assertions (
    not_null(columns := (COMPANYID, DOCUMENTCOMPANY, DOCNO, DOCTYPE, PAYITM)),
    unique_combination_of_columns(columns := (COMPANYID, DOCUMENTCOMPANY, DOCNO, DOCTYPE, PAYITM)),
    ar_reserve_forecast_gap
  )
);

WITH BASE AS (
SELECT
  @normalize_key(B.RPCO) AS COMPANYID,
  @normalize_key(B.RPKCO) AS DOCUMENTCOMPANY,
  @normalize_key(B.RPDOC) AS DOCNO,
  @normalize_key(B.RPDCT) AS DOCTYPE,
  @normalize_key(B.RPSFX) AS PAYITM,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS OPENAMOUNT,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPAAP AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS GROSSAMOUNT,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPSTAM AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS TAXAMOUNT,
  COALESCE(
    TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPDPAM AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)),
    CASE
      WHEN NULLIF(@normalize_key(B.RPADSC), '') IS NOT NULL AND @normalize_key(B.RPASTS) = 'D'
      THEN TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(B.RPAG AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2))
      ELSE 0
    END
  ) AS DISPUTEDAMOUNT,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQCRSV AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS CURRENTRESERVE,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQARSV AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS ARCURRENTRESERVE,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQPRSV AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS PREVIOUSFORECASTRESERVE,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQFR30 AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS FORECASTRESERVE30,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQFR60 AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS FORECASTRESERVE60,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQFR90 AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS FORECASTRESERVE90,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQCHRV AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS CHANGEINRESERVE,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQDFTO AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS DRAFTOPENAMOUNT,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQADJA AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS ADJUSTMENTAMOUNT,
  TRY_CAST(NULLIF(REGEXP_REPLACE(CAST(R.HQRSCA AS VARCHAR), '[^0-9.-]', ''), '') AS DECIMAL(18, 2)) AS RESERVECASHAPPLIED,
  CAST(COALESCE(R.HQAGDY, DATEDIFF('DAY', @jde_to_date(B.RPDDJ), CURRENT_DATE())) AS BIGINT) AS AGINGDAYS,
  COALESCE(
    CAST(R.HQRP AS BIGINT),
    @jde_fiscal_period_id(@jde_to_date(B.RPDGJ))
  ) AS FISCALPERIODID,
  @jde_to_date(B.RPDGJ) AS GLDATE,
  @jde_to_date(B.RPDDJ) AS DUEDATE,
  @jde_to_date(R.HQAOFD) AS AGEASOFDATE,
  @jde_to_date(R.HQLRDT) AS LATESTRECEIPTDATE,
  @jde_to_date(B.RPDPDT) AS DISPUTEDATE,
  CAST(PT.PTNDDY AS BIGINT) AS NETDAYS
FROM STAGING.F03B11 B
LEFT JOIN STAGING.F59HQ084 R
  ON @normalize_key(B.RPCO) = @normalize_key(R.HQCO)
  AND @normalize_key(B.RPDOC) = @normalize_key(R.HQDOC)
  AND @normalize_key(B.RPDCT) = @normalize_key(R.HQDCT)
  AND @normalize_key(B.RPSFX) = @normalize_key(R.HQSFX)
LEFT JOIN STAGING.F0014 PT
  ON @normalize_key(B.RPPTC) = @normalize_key(PT.PTC)
)
SELECT
  *,
  CASE
    WHEN COALESCE(AGINGDAYS, 0) <= 0 THEN 'CURRENT'
    WHEN AGINGDAYS BETWEEN 1 AND 30 THEN '1-30'
    WHEN AGINGDAYS BETWEEN 31 AND 60 THEN '31-60'
    WHEN AGINGDAYS BETWEEN 61 AND 90 THEN '61-90'
    ELSE '90+'
  END AS AGINGBUCKET,
  YEAR(GLDATE) AS FISCALYEAR,
  MONTH(GLDATE) AS FISCALMONTH,
  CURRENT_TIMESTAMP() AS INSERTDATE
FROM BASE;
