vde: false
name: service-analytics-semantic-core
display_name: Service Analytics Semantic (Core)
description: Core semantic data product for OTIS service analytics focused on standardized portfolio, reliability, and compliance reporting.
discoverable: true
version: 0.0.1
alignment: consumer_aligned
domain: service
tags:
  - Snowflake
  - Service_Analytics
  - Semantic_Core
terms:
  - glossary.data_product
  - glossary.service
  - glossary.service_analytics
  - glossary.semantic_model

gateways:
  default:
    connection:
      type: depot
      address: dataos://analyticsprod?purpose=rw

default_gateway: default

model_defaults:
  dialect: "snowflake"
  start: "2020-01-01"
  cron: "*/30 * * * *"

notification_targets:
  - type: teams_webhook
    url: "https://default2e22bdde3ec243f5bf9278e9f35a44.fb.environment.api.powerplatform.com:443/powerautomate/automations/direct/cu/17/workflows/9076978b80e545a99cc9d3570c5b350f/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=-BCV8UQ2_jbXI8kH2ye0nT3oEGY7Txlruq8n2tCX_Rk"
    notify_on:
      - apply_start
      - apply_end
      - run_start
      - run_end
      - migration_start
      - migration_end
      - apply_failure
      - run_failure
      - audit_failure
      - migration_failure
      - plan_change
      - dq_start
      - dq_end

users:
  - username: manishagrawaltmdcio
    email: manish.agrawal@tmdc.io
    type: OWNER
  - username: deepakjaiswaltmdcio
    email: deepak.jaiswal@tmdc.io
    type: DEVELOPER