name: analytics-prod-cred
version: v2alpha
type: secret
tags:
  - dataos:type:snowflake-resource
  - dataos:type:tenant-resource
  - dataos:resource:secret 
description: Stores credentials for secure Snowflake-to-DataOS connection and authentication in downstream data processes.
spec:
  type: key-value
  data:
    username: "YASHTMDC"
    password: ""
    role: "ONBOARDING"