name: jdeproduction
version: v2alpha
type: depot
tags:
  - dataos:type:snowflake-resource
  - dataos:type:tenant-resource
  - dataos:resource:depot 
  - JDE_PRODUCTION
description: Connects the Snowflake JDE_PRODUCTION database to DataOS for downstream data processing.
spec:
  type: snowflake
  spec:
    database: "JDE_PRODUCTION"
    url: "BKSFOCJ-MM27667.snowflakecomputing.com"
    warehouse: "SNOWFLAKE_LEARNING_WH"
    account: "BKSFOCJ-MM27667"
  secrets:
    - id: "otis-onboarding:analytics-prod-cred"
      purpose: rw